### ISSUE TITLE
Chore: Multi-voice audio generation

### ISSUE THREAD

**Issue by hahuyhoang411** [homebrewltd/llama3-s#12]
Motivation:
- Current dataset is mono-voice (female)
-> Model can't answer properly if the sound input is male's voice

Goal:
1. Expand the model with multiple speakers (genders, regions, innotation, etc.)
2. Create v2 dataset: 2B tokens?

Side idea:
1. Overlap audio samples: e.g.
- Speaker 1: 100 samples
- Speaker 2: 100 samples (20 samples overlap with speaker 1)

**Comment by hungphongtrn** [comment]
I created a dataset with unique speaker as a reference for WhisperSpeech here: [unique_speaker_audio](https://huggingface.co/datasets/jan-hq/unique_speaker_audio_dataset)
