### ISSUE TITLE
Gradio demo locally

### ISSUE THREAD

**Issue by yvrjsharma** [homebrewltd/llama3-s#33]
It would be helpful to have the [huggingface demo](https://huggingface.co/spaces/jan-hq/Llama3.1-s-v0.2) available in the repository and linked in the readme to improve accessibility and discoverability for the community. For example, the LivePortrait repository has a locally available demo, [as seen here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#4-gradio-interface-).

![image](https://github.com/user-attachments/assets/3bb448b7-13cd-4b77-9543-5904f5ecf414)

**Comment by bachvudinh** [comment]
Thanks for advices. We are actually hosting a demo on HF space, I just forget to add a link in the readme. Also, i just added a session with instructions to make users easier to host their own demo locally.

**Comment by yvrjsharma** [comment]
Brilliant! Thanks @bachvudinh 🙌
