### ISSUE TITLE
Confuse the max length in stage1 of llama3-s v0.2

### ISSUE THREAD

**Issue by Qoboty** [homebrewltd/llama3-s#36]
Hi, In v0.2 blog: https://homebrew.ltd//blog/llama3-just-got-ears,  I saw Max length is 4096 in stage1, 
<img width="739" alt="image" src="https://github.com/user-attachments/assets/0f3f0068-bd0b-4f4b-b48d-ffef7c591525">

but from  below link config file I saw  max_seq_len: 512 , So what's the command of stage1 by torchtune? , and Where is the yaml file of stage1 of v0.2? Thanks.
<img width="708" alt="image" src="https://github.com/user-attachments/assets/bbdb86f0-9a58-48a6-a3e8-5ae9f6ef547f">

**Comment by tikikun** [comment]
This probably is an issue with the publication, we will fix it asap
