### ISSUE TITLE
feat: Multi-turn dataset

### ISSUE THREAD

**Issue by 0xSage** [homebrewltd/llama3-s#39]

**Comment by bachvudinh** [comment]
I uploaded all the multiturn sample here: https://drive.google.com/file/d/1CeXWmhrZZa2fhFKVh1fmSm7q5mfm9XGZ/view?usp=drive_link. 

Total number of multi-turn sample is: 65472
cc @0xSage @tikikun

**Comment by tikikun** [comment]
The number is still a bit too conservative, can you find a few more dataset that has extra multi turn data

**Comment by bachvudinh** [comment]
https://huggingface.co/datasets/BAAI/Infinity-Instruct
https://huggingface.co/datasets/Magpie-Align/Magpie-Pro-300K-Filtered
for the multi turn dataset here is 2 very clean set that enough for us to train next step
