### ISSUE TITLE
feat: Re-generate dataset with updated tokenizer

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/llama3-s#42]
We will change tokenizer for the next version of the updated model

**Comment by tikikun** [comment]
hi @bachvudinh per your concern, please download and further expand the training set with this data

https://huggingface.co/datasets/facebook/multilingual_librispeech

**Comment by bachvudinh** [comment]
the dataset are uploaded on the HF here: https://huggingface.co/datasets/homebrewltd/raw-speech-whispervq-v2.
and on internal s3: myminio/data/FB_multilingual_librispeech/
cc @tikikun

**Comment by tikikun** [comment]
it's done
