### ISSUE TITLE
feat: rewrite "As an AI language model" in our dataset

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/llama3-s#45]
We need to rewrite this using llama3.1 bigger model or sth to change the tongue back to original tongue of the model

**Comment by bachvudinh** [comment]
add answer for background noise sample: https://huggingface.co/datasets/Myrtle/CAIMAN-ASR-BackgroundNoise.

**Comment by tikikun** [comment]
QA dataset, need to review the process one more time before finish

**Comment by bachvudinh** [comment]
Done using Distilable: https://huggingface.co/datasets/homebrewltd/prompt-voice-v1-repharase.
