### ISSUE TITLE
Epic: Training Data Quality Checking.

### ISSUE THREAD

**Issue by bachvudinh** [homebrewltd/llama3-s#5]
Identify and list all data items with queries that are not suitable for use as input sounds in training data: jan-hq/instruction-speech-v1.5 and jan-hq/instruction-speech-v1.

**Comment by bachvudinh** [comment]
here are some examples:
query containing complicated http link:
<img width="511" alt="Screenshot_2024-07-12_at_15 12 17" src="https://github.com/user-attachments/assets/e27ca2a3-c403-4ec4-a61e-5702dd7363df">
query that input a complicated sentence  or paragraph:
![Uploading Screenshot_2024-07-12_at_15.12.17.png…]()

**Comment by hahuyhoang411** [comment]
Sentence has `Q:` `A:` 
![image](https://github.com/user-attachments/assets/808b2314-0d11-4d19-89b3-04db6e835b71)

**Comment by hahuyhoang411** [comment]
This makes no sense for a voice instruction
![image](https://github.com/user-attachments/assets/b9062cf6-7252-4482-b090-191294488223)

may need an small LLM to filter?

**Comment by hahuyhoang411** [comment]
This type of math is quite unsuitable when it comes to voice instruction

![image](https://github.com/user-attachments/assets/a5db8b8e-cb43-47c7-bf41-3173e81ba1ff)

**Comment by hahuyhoang411** [comment]
weird symbol -> this could be hard for creating audio 
![image](https://github.com/user-attachments/assets/fb1778e9-5ff1-4212-a76f-a75b9ec2827c)

**Comment by hahuyhoang411** [comment]
Also take a close look at sample has ":"
![image](https://github.com/user-attachments/assets/9232e195-a80d-43d1-8e78-24b2e0e53098)

The audio file is unclear. (check the sample 2)

https://huggingface.co/datasets/jan-hq/instruction-speech-v1.5-conversation

**Comment by hungphongtrn** [comment]
In conversation, i think that special tokens such as "(", ")", "{" will never be spoken out. Maybe we should filter our these tokens before send it to TTS.
![image](https://github.com/user-attachments/assets/dfe7786f-e968-4bb4-a977-6a2ebe0792a6)

**Comment by hahuyhoang411** [comment]
Note after reviewing:
- We might not need Bert for these
- We should have a filter to exclude:
  - Specific tasks
  - Special tokens

**Comment by hungphongtrn** [comment]
> Note after reviewing:
> 
> * We might not need Bert for these
> * We should have a filter to exclude:
>   
>   * Specific tasks
>   * Special tokens

I came across this tool. https://github.com/modelscope/data-juicer?tab=readme-ov-file. Hopefully it's helpful.

**Comment by bachvudinh** [comment]
OMG found an series of audio instruction dataset that can be used to benchmark our models: https://huggingface.co/AudioLLMs. They used a lot of data from open benchmark and keep the cleaned and audio-compatible data. @hahuyhoang411

**Comment by tikikun** [comment]
Done for first release
