### ISSUE TITLE
Training: Debug degradation issue

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/llama3-s#50]
Recovery pattern changed, need to figure out how to recover mmlu score

**Comment by bachvudinh** [comment]
Here is the MMLU results:
- Checkpoint step 1000:

![Image](https://github.com/user-attachments/assets/799ddd0c-57cb-47f5-a905-5708bc6287df)

- Checkpoint step 2000:

![Image](https://github.com/user-attachments/assets/4cc8bc33-d50b-492b-ac24-ac46fefdcf21)

- Checkpoints step 3000: 

![Image](https://github.com/user-attachments/assets/416a746e-0c1e-4440-b958-6f4a1d6d8dc7)

- Final checkpoint(3800 step):

**Comment by bachvudinh** [comment]
Audio Bench Result:

- Checkpoint step 1000:

- Checkpoint step 2000:

- Checkpoint step 3000:

- Final checkpoint(3800 step):

**Comment by tikikun** [comment]
| Test Name       | Description                                            | Status | Result     |
|-----------------|--------------------------------------------------------|--------|------------|
| Test 1          | Pretrain checkpoint: 3000 steps, 500k mixed dataset    | Done   | MMLU recover from 0.3 -> 0.55   |
| Test 2          | Pretrain checkpoint full pretrain, 5000k mixed dataset | Not yet | Not yet |

**Comment by tikikun** [comment]
@bachvudinh can you add the data directly here

**Comment by bachvudinh** [comment]
New training run result:
MMLU benchmark:
- Checkpoint step 2000:

![Screenshot from 2024-09-10 10-13-07](https://github.com/user-attachments/assets/afd6eca3-3cc4-46ff-91e1-bdb1d865874f)

- Checkpoint end epoch(step 3800):

![Screenshot from 2024-09-10 10-51-22](https://github.com/user-attachments/assets/cdac9100-4e15-47f5-832e-dbf73203f650)

Speech Instruction Benchmark:

- Checkpoint end epoch: 
  + alpaca: "judge_score": 2.97,
  + open hermes: "judge_score": 3.01,

**Comment by bachvudinh** [comment]
Test 2: Training with transcription results:
MMLU results:
- checkpoint step 1000:

![Screenshot from 2024-09-09 20-12-50](https://github.com/user-attachments/assets/32905202-0dff-483e-96de-22d4de716b1b)

- checkpoint step 2000:

![Screenshot from 2024-09-09 20-35-40](https://github.com/user-attachments/assets/73a7a1ec-7397-4ae6-9b4d-e3fa83b5197f)

- checkpoint step 3000:

![Screenshot from 2024-09-09 21-02-35](https://github.com/user-attachments/assets/f5ab447d-94c2-44da-b95c-2946f7120936)

- Checkpoint step 4000:

![Screenshot from 2024-09-09 21-32-52](https://github.com/user-attachments/assets/0b07f55c-d40b-4453-820c-4f4728d28b18)

**Comment by tikikun** [comment]
Follow-ups:
- It seems that further pretrain will slow down the speed of MMLU recovery, but not too far off (55 vs 51)
- Per qualitative checking, and scoring wise (alpaca/openhermes audio) it's cleary that further pretrain has positive impact on the model ability to converge to instruction ability
- Adding filtering token and transcription in step 3 slow down the recovery speed of mmlu

Conclusions + Actions:
- The model can recover drastically from MMLU 0.3 regardless of longer pretrain, we need more instruction tune data (which we already have, the test is just on subset)
- Mixed transcription may cause unwanted effects on mmlu ability -> replace transcription with segmenting strategy, the dataset will have only transcription data in the beginning and change to instruction on the latter part

**Comment by tikikun** [comment]
Probably we will need 2 more runs to get to the best quality of the training run.

**Comment by tikikun** [comment]
Issue solve, reaching final run
