### ISSUE TITLE
chore: centralize data for second run

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/llama3-s#53]
- Full version of data in text only
- Full version of data in sound token (need readme description)

**Comment by bachvudinh** [comment]
here is the full data i just push to HF: https://huggingface.co/datasets/homebrewltd/instruction-text-only-full.

**Comment by bachvudinh** [comment]
All our training data:
- Pretraining data: https://huggingface.co/datasets/homebrewltd/raw-speech-whispervq-v2. 
- Instruction tuning data:
   + Text-only : https://huggingface.co/datasets/homebrewltd/instruction-text-only-full.
   + Sound instruction: we have 2 subset: https://huggingface.co/datasets/homebrewltd/instruction-speech-whispervq-v3-subset-1 and https://huggingface.co/datasets/homebrewltd/instruction-speech-whispervq-v3-subset-2
   + Rephrase using distilable: https://huggingface.co/datasets/homebrewltd/prompt-voice-v1-repharase.
  + final mixed dataset with 10% text-only and 30% transcription data: https://huggingface.co/datasets/homebrewltd/mixed-instruction-speech-whispervq-v3-full.

**Comment by tikikun** [comment]
@
